name: deepcontact-env
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - biopython==1.70
  - h5py==2.7.1
  - numpy==1.13.3
  - pyyaml==3.12
  - scipy==1.0.0
  - six==1.11.0
  - subprocess32==3.2.7
  - theano==0.8.0
